title: Nighthawk Pages 
description: "Class of 2025"
owner_name: John Mortensen
github_username: rc765445
github_repo: "rutvik_2025" 
baseurl: "/rutvik_2025"
future: true
# remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
<<<<<<< HEAD
# remote_theme: pages-themes/midnight@v0.2.0
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
  remote_theme: pages-themes/cayman@v0.2.0
=======
=======
remote_theme: pages-themes/midnight@v0.2.0
>>>>>>> parent of ee65e0e (theme change)
# remote_theme: pages-themes/cayman@v0.2.0
>>>>>>> parent of 7766bd3 (theme change 2)
=======
 remote_theme: pages-themes/cayman@v0.2.0
>>>>>>> parent of 3e345f1 (spacing)
=======
  remote_theme: pages-themes/cayman@v0.2.0
>>>>>>> parent of 46037bd (spacing 2)
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/journey.md
  - _notebooks/python
  - README4YML.md
